"use strict";(()=>{var e={};e.id=386,e.ids=[386],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},27790:e=>{e.exports=require("assert")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},17702:e=>{e.exports=require("events")},32615:e=>{e.exports=require("http")},35240:e=>{e.exports=require("https")},86624:e=>{e.exports=require("querystring")},17360:e=>{e.exports=require("url")},21764:e=>{e.exports=require("util")},71568:e=>{e.exports=require("zlib")},23940:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>f,patchFetch:()=>v,requestAsyncStorage:()=>g,routeModule:()=>x,serverHooks:()=>y,staticGenerationAsyncStorage:()=>h});var s={};r.r(s),r.d(s,{GET:()=>m,POST:()=>d,dynamic:()=>l});var n=r(79182),o=r(72007),a=r(56719),i=r(93442),p=r(97563),c=r(91209);let l="force-dynamic",u=c.z.object({name:c.z.string().min(2,"Nom trop court"),email:c.z.string().email("Email invalide"),phone:c.z.string().optional(),message:c.z.string().min(10,"Message trop court"),honeypot:c.z.string().optional()});async function d(e){try{let t=await e.json(),r=u.safeParse(t);if(!r.success)return i.NextResponse.json({error:"Donn\xe9es invalides",details:r.error.flatten().fieldErrors},{status:400});let s=r.data;if(s.honeypot&&s.honeypot.length>0)return i.NextResponse.json({success:!0,message:"Message envoy\xe9"});let n=await p._.contact.create({data:{name:s.name,email:s.email,phone:s.phone??null,message:s.message,status:"new"}});try{let e=process.env.NEXTAUTH_URL??"",t="declic";try{t=new URL(e).hostname?.split(".")?.[0]??"declic"}catch{}let r=`
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #E8734A; border-bottom: 2px solid #E8734A; padding-bottom: 10px;">Nouveau message de contact</h2>
          <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 10px 0;"><strong>Nom :</strong> ${s.name}</p>
            <p style="margin: 10px 0;"><strong>Email :</strong> <a href="mailto:${s.email}">${s.email}</a></p>
            ${s.phone?`<p style="margin: 10px 0;"><strong>T\xe9l\xe9phone :</strong> ${s.phone}</p>`:""}
            <p style="margin: 10px 0;"><strong>Message :</strong></p>
            <div style="background: white; padding: 15px; border-radius: 4px; border-left: 4px solid #E8734A;">
              ${s.message}
            </div>
          </div>
        </div>
      `;await fetch("https://apps.abacus.ai/api/sendNotificationEmail",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({deployment_token:process.env.ABACUSAI_API_KEY,app_id:process.env.WEB_APP_ID,notification_id:process.env.NOTIF_ID_NOUVEAU_MESSAGE_DE_CONTACT,subject:`Nouveau message de ${s.name} - D\xe9clic`,body:r,is_html:!0,recipient_email:"contact@declic.fr",reply_to:s.email,sender_email:`noreply@${t}`,sender_alias:"D\xe9clic"})})}catch(e){console.error("Email notification error:",e)}return i.NextResponse.json({success:!0,message:"Message envoy\xe9 avec succ\xe8s",id:n.id})}catch(e){return console.error("Contact error:",e),i.NextResponse.json({error:"Erreur lors de l'envoi"},{status:500})}}async function m(e){try{let{getServerSession:e}=await r.e(978).then(r.t.bind(r,57978,23)),{authOptions:t}=await Promise.all([r.e(390),r.e(826)]).then(r.bind(r,11826));if(!await e(t))return i.NextResponse.json({error:"Non autoris\xe9"},{status:401});let s=await p._.contact.findMany({orderBy:{createdAt:"desc"}});return i.NextResponse.json(s)}catch(e){return console.error("Get contacts error:",e),i.NextResponse.json({error:"Erreur serveur"},{status:500})}}let x=new n.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/contact/route",pathname:"/api/contact",filename:"route",bundlePath:"app/api/contact/route"},resolvedPagePath:"/home/ubuntu/declic_agency/nextjs_space/app/api/contact/route.ts",nextConfigOutput:"",userland:s}),{requestAsyncStorage:g,staticGenerationAsyncStorage:h,serverHooks:y}=x,f="/api/contact/route";function v(){return(0,a.patchFetch)({serverHooks:y,staticGenerationAsyncStorage:h})}},97563:(e,t,r)=>{r.d(t,{_:()=>n});let s=require("@prisma/client"),n=globalThis.prisma??new s.PrismaClient}};var t=require("../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[412,609,209],()=>r(23940));module.exports=s})();