"use strict";(()=>{var e={};e.id=324,e.ids=[324],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},27790:e=>{e.exports=require("assert")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},17702:e=>{e.exports=require("events")},32615:e=>{e.exports=require("http")},35240:e=>{e.exports=require("https")},86624:e=>{e.exports=require("querystring")},17360:e=>{e.exports=require("url")},21764:e=>{e.exports=require("util")},71568:e=>{e.exports=require("zlib")},1727:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>f,patchFetch:()=>v,requestAsyncStorage:()=>x,routeModule:()=>g,serverHooks:()=>h,staticGenerationAsyncStorage:()=>y});var o={};r.r(o),r.d(o,{GET:()=>m,POST:()=>d,dynamic:()=>c});var n=r(79182),s=r(72007),i=r(56719),a=r(93442),l=r(97563),p=r(91209);let c="force-dynamic",u=p.z.object({customerName:p.z.string().min(2,"Nom trop court"),email:p.z.string().email("Email invalide"),phone:p.z.string().optional(),date:p.z.string(),timeSlot:p.z.string(),serviceType:p.z.string().optional(),notes:p.z.string().optional()});async function d(e){try{let t=await e.json(),r=u.safeParse(t);if(!r.success)return a.NextResponse.json({error:"Donn\xe9es invalides",details:r.error.flatten().fieldErrors},{status:400});let o=r.data,n=new Date(o.date);if(await l._.booking.findFirst({where:{date:n,timeSlot:o.timeSlot,status:{not:"cancelled"}}}))return a.NextResponse.json({error:"Ce cr\xe9neau est d\xe9j\xe0 r\xe9serv\xe9. Veuillez en choisir un autre."},{status:409});let s=await l._.booking.create({data:{customerName:o.customerName,email:o.email,phone:o.phone??null,date:n,timeSlot:o.timeSlot,serviceType:o.serviceType??"diagnostic",notes:o.notes??null,status:"confirmed"}});try{let e=process.env.NEXTAUTH_URL??"",t="declic";try{t=new URL(e).hostname?.split(".")?.[0]??"declic"}catch{}let r=n.toLocaleDateString("fr-FR",{weekday:"long",year:"numeric",month:"long",day:"numeric"}),s=`
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #E8734A; border-bottom: 2px solid #E8734A; padding-bottom: 10px;">Nouvelle r\xe9servation de diagnostic</h2>
          <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 10px 0;"><strong>Nom :</strong> ${o.customerName}</p>
            <p style="margin: 10px 0;"><strong>Email :</strong> <a href="mailto:${o.email}">${o.email}</a></p>
            ${o.phone?`<p style="margin: 10px 0;"><strong>T\xe9l\xe9phone :</strong> ${o.phone}</p>`:""}
            <p style="margin: 10px 0;"><strong>Date :</strong> ${r}</p>
            <p style="margin: 10px 0;"><strong>Cr\xe9neau :</strong> ${o.timeSlot}</p>
            ${o.notes?`<p style="margin: 10px 0;"><strong>Notes :</strong> ${o.notes}</p>`:""}
          </div>
        </div>
      `;await fetch("https://apps.abacus.ai/api/sendNotificationEmail",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({deployment_token:process.env.ABACUSAI_API_KEY,app_id:process.env.WEB_APP_ID,notification_id:process.env.NOTIF_ID_CONFIRMATION_DE_RSERVATION,subject:`Nouvelle r\xe9servation - ${o.customerName} - D\xe9clic`,body:s,is_html:!0,recipient_email:"contact@declic.fr",reply_to:o.email,sender_email:`noreply@${t}`,sender_alias:"D\xe9clic"})})}catch(e){console.error("Booking email error:",e)}return a.NextResponse.json({success:!0,message:"R\xe9servation confirm\xe9e",id:s.id})}catch(e){return console.error("Booking error:",e),a.NextResponse.json({error:"Erreur lors de la r\xe9servation"},{status:500})}}async function m(e){try{let t=new URL(e.url).searchParams.get("date");if(t){let e=new Date(t),r=await l._.booking.findMany({where:{date:e,status:{not:"cancelled"}},select:{timeSlot:!0}});return a.NextResponse.json(r?.map(e=>e?.timeSlot)??[])}let{getServerSession:o}=await r.e(978).then(r.t.bind(r,57978,23)),{authOptions:n}=await Promise.all([r.e(390),r.e(826)]).then(r.bind(r,11826));if(!await o(n))return a.NextResponse.json({error:"Non autoris\xe9"},{status:401});let s=await l._.booking.findMany({orderBy:{date:"desc"}});return a.NextResponse.json(s)}catch(e){return console.error("Get bookings error:",e),a.NextResponse.json({error:"Erreur serveur"},{status:500})}}let g=new n.AppRouteRouteModule({definition:{kind:s.x.APP_ROUTE,page:"/api/booking/route",pathname:"/api/booking",filename:"route",bundlePath:"app/api/booking/route"},resolvedPagePath:"/home/ubuntu/declic_agency/nextjs_space/app/api/booking/route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:x,staticGenerationAsyncStorage:y,serverHooks:h}=g,f="/api/booking/route";function v(){return(0,i.patchFetch)({serverHooks:h,staticGenerationAsyncStorage:y})}},97563:(e,t,r)=>{r.d(t,{_:()=>n});let o=require("@prisma/client"),n=globalThis.prisma??new o.PrismaClient}};var t=require("../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),o=t.X(0,[412,609,209],()=>r(1727));module.exports=o})();